server:
  port: 8881

logging.config: classpath:logback-spring.xml

spring.http.encoding:
  force: true
  enabled: true
  charset: UTF-8

server.tomcat.uri-encoding: UTF-8

#management.security.enabled: false # spring-boot 1.5.x 版本中通过management.security.enabled=false来暴露所有端点
management:
  endpoints.web:
    exposure.include: '*' # spring-boot 2.0 暴露所有端点的方式

spring:
  application.name: gateway
  cloud.gateway.routes:
    - id: demo
      url: http://www.google.com
      predicates:
      - Path=/demo/{segment},/api/demo/{segment}
      filters:
      - name: Hystrix
        args:
          name: fetchIngredients
          fallbackUri: forward:/fallback
    - id: demo-fallback
      uri: http://127.0.0.1:9994
      predicates:
      - Path=/fallback

hystrix.command.fallbackcmd.execution.isolation.thread.timeoutInMilliseconds: 5000
