spring:
  application:
    name: demo

server:
  port: 8801

com.neo:
  title: 2333
  description: 233333

jdbc:
  company:
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/fgo?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  home:
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/home?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root

eureka:
  client:
    enabled: true
    serviceUrl.defaultZone: http://127.0.0.1:8701/eureka/
    registry-fetch-interval-seconds: 5 # 每隔2秒从服务端获取最新的注册信息,如果获取超时，第二次获取时间会翻倍
    register.with.eureka: true # 注册到eureka
    fetch.registry: true # 从eureka获取其他服务的注册信息
    instance-info-replication-interval-seconds: 5 # 每隔5秒扫描一次本地实例，如果有变化向服务重新注册

spring.http.encoding.force: true
spring.http.encoding.enabled: true
spring.http.encoding.charset: UTF-8

server.tomcat.uri-encoding: UTF-8

logging.config: classpath:logback-spring.xml

spring.thymeleaf.prefix: classpath:/page/

