spring:
  application:
    name: demo

server:
  port: 8801

com.neo:
  title: 2333
  description: 233333

jdbc:
  company:
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/fgo?useUnicode: true&characterEncoding: utf-8
    username: root
    password: root
  home:
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/home?useUnicode: true&characterEncoding: utf-8
    username: root
    password: root

server.port: 9999
spring.http.encoding.force: true
spring.http.encoding.enabled: true
spring.http.encoding.charset: UTF-8

server.tomcat.uri-encoding: UTF-8

logging.config: classpath:logback-spring.xml

spring.thymeleaf.prefix: classpath:/page/

