spring:
  application:
    name: eureka-server

server:
  port: 8702

eureka:
  server:
    enableSelfPreservation: false
  instance:
    prefer-ip-address: false
    hostname: eureka2
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://eureka1:8701/eureka/,http://eureka3:8703/eureka/
