spring:
  application:
    name: eureka-server

server:
  port: 8703

eureka:
  server:
    enableSelfPreservation: false
  instance:
    prefer-ip-address: false
    hostname: eureka3
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://eureka2:8701/eureka/,http://eureka3:8702/eureka/
