spring:
  application:
    name: eureka-server

server:
  port: 8703

eureka:
  server:
    enableSelfPreservation: false
  instance:
    hostname: eureka3
  client:
    #healthcheck.enabled: true #使用health端点来代替心跳表明服务是否可用，反应到eureka server ui上服务的UP还是DOWN
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://eureka1:8701/eureka/,http://eureka2:8702/eureka/,http://eureka3:8703/eureka/
