spring:
  application:
    name: eureka-server

server:
  port: 8701

eureka:
  server:
    enableSelfPreservation: false
  instance:
    hostname: eureka1
  client:
    #healthcheck.enabled: true #使用health端点来代替心跳表明服务是否可用，反应到eureka server ui上服务的UP还是DOWN
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://eureka1:8701/eureka/

# 不加这个prometheus日志上就会报错，不知道为啥，
spring.mvc.async.request-timeout: -1
